# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/all_programs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_all_programs_form(object):
    def setupUi(self, all_programs_form):
        all_programs_form.setObjectName("all_programs_form")
        all_programs_form.resize(530, 350)
        self.win_all_programs = QtWidgets.QFrame(all_programs_form)
        self.win_all_programs.setGeometry(QtCore.QRect(0, 0, 530, 350))
        self.win_all_programs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.win_all_programs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.win_all_programs.setObjectName("win_all_programs")

        self.retranslateUi(all_programs_form)
        QtCore.QMetaObject.connectSlotsByName(all_programs_form)

    def retranslateUi(self, all_programs_form):
        _translate = QtCore.QCoreApplication.translate
        all_programs_form.setWindowTitle(_translate("all_programs_form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    all_programs_form = QtWidgets.QWidget()
    ui = Ui_all_programs_form()
    ui.setupUi(all_programs_form)
    all_programs_form.show()
    sys.exit(app.exec_())
