# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/back_ok_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_back_ok_buttons_form(object):
    def setupUi(self, back_ok_buttons_form):
        back_ok_buttons_form.setObjectName("back_ok_buttons_form")
        back_ok_buttons_form.resize(1002, 80)
        self.back_ok_buttons_win = QtWidgets.QFrame(back_ok_buttons_form)
        self.back_ok_buttons_win.setGeometry(QtCore.QRect(0, 0, 1002, 80))
        self.back_ok_buttons_win.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_ok_buttons_win.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_ok_buttons_win.setObjectName("back_ok_buttons_win")
        self.btn_back_for_all = QtWidgets.QPushButton(self.back_ok_buttons_win)
        self.btn_back_for_all.setGeometry(QtCore.QRect(700, 5, 120, 70))
        self.btn_back_for_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"alternate-background-color: rgb(255, 0, 0);")
        self.btn_back_for_all.setObjectName("btn_back_for_all")
        self.btn_ok_for_all = QtWidgets.QPushButton(self.back_ok_buttons_win)
        self.btn_ok_for_all.setGeometry(QtCore.QRect(850, 5, 120, 70))
        self.btn_ok_for_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 255);\n"
"alternate-background-color: rgb(85, 85, 255);")
        self.btn_ok_for_all.setObjectName("btn_ok_for_all")

        self.retranslateUi(back_ok_buttons_form)
        QtCore.QMetaObject.connectSlotsByName(back_ok_buttons_form)

    def retranslateUi(self, back_ok_buttons_form):
        _translate = QtCore.QCoreApplication.translate
        back_ok_buttons_form.setWindowTitle(_translate("back_ok_buttons_form", "Form"))
        self.btn_back_for_all.setText(_translate("back_ok_buttons_form", "BACK"))
        self.btn_ok_for_all.setText(_translate("back_ok_buttons_form", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    back_ok_buttons_form = QtWidgets.QWidget()
    ui = Ui_back_ok_buttons_form()
    ui.setupUi(back_ok_buttons_form)
    back_ok_buttons_form.show()
    sys.exit(app.exec_())
