# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/cancel_ok_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cancel_ok_buttons_form(object):
    def setupUi(self, cancel_ok_buttons_form):
        cancel_ok_buttons_form.setObjectName("cancel_ok_buttons_form")
        cancel_ok_buttons_form.resize(1002, 80)
        self.cancel_ok_buttons_win = QtWidgets.QFrame(cancel_ok_buttons_form)
        self.cancel_ok_buttons_win.setGeometry(QtCore.QRect(0, 0, 1002, 80))
        self.cancel_ok_buttons_win.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cancel_ok_buttons_win.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cancel_ok_buttons_win.setObjectName("cancel_ok_buttons_win")
        self.btn_cancel_for_all = QtWidgets.QPushButton(self.cancel_ok_buttons_win)
        self.btn_cancel_for_all.setGeometry(QtCore.QRect(700, 5, 120, 70))
        self.btn_cancel_for_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"alternate-background-color: rgb(255, 85, 0);")
        self.btn_cancel_for_all.setObjectName("btn_cancel_for_all")
        self.btn_ok_for_all = QtWidgets.QPushButton(self.cancel_ok_buttons_win)
        self.btn_ok_for_all.setGeometry(QtCore.QRect(850, 5, 120, 70))
        self.btn_ok_for_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);\n"
"alternate-background-color: rgb(85, 170, 127);")
        self.btn_ok_for_all.setObjectName("btn_ok_for_all")

        self.retranslateUi(cancel_ok_buttons_form)
        QtCore.QMetaObject.connectSlotsByName(cancel_ok_buttons_form)

    def retranslateUi(self, cancel_ok_buttons_form):
        _translate = QtCore.QCoreApplication.translate
        cancel_ok_buttons_form.setWindowTitle(_translate("cancel_ok_buttons_form", "Form"))
        self.btn_cancel_for_all.setText(_translate("cancel_ok_buttons_form", "CANCEL"))
        self.btn_ok_for_all.setText(_translate("cancel_ok_buttons_form", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cancel_ok_buttons_form = QtWidgets.QWidget()
    ui = Ui_cancel_ok_buttons_form()
    ui.setupUi(cancel_ok_buttons_form)
    cancel_ok_buttons_form.show()
    sys.exit(app.exec_())
