# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/charge_constant_current.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_charge_constant_current_form(object):
    def setupUi(self, charge_constant_current_form):
        charge_constant_current_form.setObjectName("charge_constant_current_form")
        charge_constant_current_form.resize(750, 430)
        self.win_charge_constant_current = QtWidgets.QFrame(charge_constant_current_form)
        self.win_charge_constant_current.setGeometry(QtCore.QRect(0, 0, 750, 430))
        self.win_charge_constant_current.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.win_charge_constant_current.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.win_charge_constant_current.setFrameShadow(QtWidgets.QFrame.Raised)
        self.win_charge_constant_current.setObjectName("win_charge_constant_current")
        self.groupBox = QtWidgets.QGroupBox(self.win_charge_constant_current)
        self.groupBox.setGeometry(QtCore.QRect(25, 15, 700, 60))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.set_current_for_charge_constant_current = QtWidgets.QLineEdit(self.groupBox)
        self.set_current_for_charge_constant_current.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_current_for_charge_constant_current.setInputMask("")
        self.set_current_for_charge_constant_current.setObjectName("set_current_for_charge_constant_current")
        self.set_charge_current_btn_for_charge_constant_current = QtWidgets.QPushButton(self.groupBox)
        self.set_charge_current_btn_for_charge_constant_current.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_charge_current_btn_for_charge_constant_current.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_charge_current_btn_for_charge_constant_current.setObjectName("set_charge_current_btn_for_charge_constant_current")
        self.groupBox_2 = QtWidgets.QGroupBox(self.win_charge_constant_current)
        self.groupBox_2.setGeometry(QtCore.QRect(25, 100, 700, 60))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.set_charge_time_btn_for_charge_constant_current = QtWidgets.QPushButton(self.groupBox_2)
        self.set_charge_time_btn_for_charge_constant_current.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_charge_time_btn_for_charge_constant_current.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_charge_time_btn_for_charge_constant_current.setObjectName("set_charge_time_btn_for_charge_constant_current")
        self.set_time_for_charge_constant_current = QtWidgets.QLineEdit(self.groupBox_2)
        self.set_time_for_charge_constant_current.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_time_for_charge_constant_current.setObjectName("set_time_for_charge_constant_current")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.win_charge_constant_current)
        self.groupBox_3.setGeometry(QtCore.QRect(25, 185, 700, 60))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.set_charge_voltage_btn_for_charge_constant_current = QtWidgets.QPushButton(self.groupBox_3)
        self.set_charge_voltage_btn_for_charge_constant_current.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_charge_voltage_btn_for_charge_constant_current.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_charge_voltage_btn_for_charge_constant_current.setObjectName("set_charge_voltage_btn_for_charge_constant_current")
        self.set_voltage_for_charge_constant_current = QtWidgets.QLineEdit(self.groupBox_3)
        self.set_voltage_for_charge_constant_current.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_voltage_for_charge_constant_current.setObjectName("set_voltage_for_charge_constant_current")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.win_charge_constant_current)
        self.groupBox_4.setGeometry(QtCore.QRect(25, 355, 700, 60))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.set_optional_alerts_btn_for_charge_constant_current = QtWidgets.QPushButton(self.groupBox_4)
        self.set_optional_alerts_btn_for_charge_constant_current.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_optional_alerts_btn_for_charge_constant_current.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_optional_alerts_btn_for_charge_constant_current.setObjectName("set_optional_alerts_btn_for_charge_constant_current")
        self.set_optional_alerts_for_charge_constant_current = QtWidgets.QLineEdit(self.groupBox_4)
        self.set_optional_alerts_for_charge_constant_current.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_optional_alerts_for_charge_constant_current.setObjectName("set_optional_alerts_for_charge_constant_current")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.win_charge_constant_current)
        self.groupBox_5.setGeometry(QtCore.QRect(25, 270, 700, 60))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.set_terminate_when_btn_for_charge_constant_current = QtWidgets.QPushButton(self.groupBox_5)
        self.set_terminate_when_btn_for_charge_constant_current.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_terminate_when_btn_for_charge_constant_current.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_terminate_when_btn_for_charge_constant_current.setObjectName("set_terminate_when_btn_for_charge_constant_current")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.terminate_on_time_for_charge_constant_current = QtWidgets.QRadioButton(self.groupBox_5)
        self.terminate_on_time_for_charge_constant_current.setGeometry(QtCore.QRect(300, 20, 90, 20))
        self.terminate_on_time_for_charge_constant_current.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.terminate_on_time_for_charge_constant_current.setObjectName("terminate_on_time_for_charge_constant_current")
        self.terminate_on_voltage_for_charge_constant_current = QtWidgets.QRadioButton(self.groupBox_5)
        self.terminate_on_voltage_for_charge_constant_current.setGeometry(QtCore.QRect(410, 20, 90, 20))
        self.terminate_on_voltage_for_charge_constant_current.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.terminate_on_voltage_for_charge_constant_current.setObjectName("terminate_on_voltage_for_charge_constant_current")

        self.retranslateUi(charge_constant_current_form)
        QtCore.QMetaObject.connectSlotsByName(charge_constant_current_form)

    def retranslateUi(self, charge_constant_current_form):
        _translate = QtCore.QCoreApplication.translate
        charge_constant_current_form.setWindowTitle(_translate("charge_constant_current_form", "Form"))
        self.label.setText(_translate("charge_constant_current_form", "CHARGE CURRENT"))
        self.set_current_for_charge_constant_current.setText(_translate("charge_constant_current_form", "PRESS TO CHANGE"))
        self.set_charge_current_btn_for_charge_constant_current.setText(_translate("charge_constant_current_form", ">"))
        self.set_charge_time_btn_for_charge_constant_current.setText(_translate("charge_constant_current_form", ">"))
        self.set_time_for_charge_constant_current.setText(_translate("charge_constant_current_form", "PRESS TO CHANGE"))
        self.label_2.setText(_translate("charge_constant_current_form", "CHARGE TIME"))
        self.set_charge_voltage_btn_for_charge_constant_current.setText(_translate("charge_constant_current_form", ">"))
        self.set_voltage_for_charge_constant_current.setText(_translate("charge_constant_current_form", "PRESS TO CHANGE"))
        self.label_3.setText(_translate("charge_constant_current_form", "CHARGE VOLTAGE"))
        self.set_optional_alerts_btn_for_charge_constant_current.setText(_translate("charge_constant_current_form", ">"))
        self.set_optional_alerts_for_charge_constant_current.setText(_translate("charge_constant_current_form", "PRESS TO CHANGE"))
        self.label_5.setText(_translate("charge_constant_current_form", "OPTIONAL ALERT (S)"))
        self.set_terminate_when_btn_for_charge_constant_current.setText(_translate("charge_constant_current_form", ">"))
        self.label_4.setText(_translate("charge_constant_current_form", "TERMINATE WHEN"))
        self.terminate_on_time_for_charge_constant_current.setText(_translate("charge_constant_current_form", "ON ONE"))
        self.terminate_on_voltage_for_charge_constant_current.setText(_translate("charge_constant_current_form", "ON BOTH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    charge_constant_current_form = QtWidgets.QWidget()
    ui = Ui_charge_constant_current_form()
    ui.setupUi(charge_constant_current_form)
    charge_constant_current_form.show()
    sys.exit(app.exec_())
