# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/christie_logo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logo_christie_form(object):
    def setupUi(self, logo_christie_form):
        logo_christie_form.setObjectName("logo_christie_form")
        logo_christie_form.resize(750, 430)
        self.win_christie_logo = QtWidgets.QFrame(logo_christie_form)
        self.win_christie_logo.setGeometry(QtCore.QRect(0, 0, 750, 430))
        self.win_christie_logo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.win_christie_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.win_christie_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.win_christie_logo.setObjectName("win_christie_logo")
        self.label = QtWidgets.QLabel(self.win_christie_logo)
        self.label.setGeometry(QtCore.QRect(75, 65, 600, 300))
        self.label.setStyleSheet("color: rgb(0, 170, 255);\n"
"font: 87 48pt \"Arial Black\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(logo_christie_form)
        QtCore.QMetaObject.connectSlotsByName(logo_christie_form)

    def retranslateUi(self, logo_christie_form):
        _translate = QtCore.QCoreApplication.translate
        logo_christie_form.setWindowTitle(_translate("logo_christie_form", "Form"))
        self.label.setText(_translate("logo_christie_form", "C H R I S T I E"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    logo_christie_form = QtWidgets.QWidget()
    ui = Ui_logo_christie_form()
    ui.setupUi(logo_christie_form)
    logo_christie_form.show()
    sys.exit(app.exec_())
