# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/current_programs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_current_programs_form(object):
    def setupUi(self, current_programs_form):
        current_programs_form.setObjectName("current_programs_form")
        current_programs_form.resize(530, 350)
        self.win_current_programs = QtWidgets.QFrame(current_programs_form)
        self.win_current_programs.setGeometry(QtCore.QRect(0, 0, 530, 350))
        self.win_current_programs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.win_current_programs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.win_current_programs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.win_current_programs.setObjectName("win_current_programs")
        self.frame_2 = QtWidgets.QFrame(self.win_current_programs)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 440, 330))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.current_programs_tasks_view = QtWidgets.QTableWidget(self.frame_2)
        self.current_programs_tasks_view.setGeometry(QtCore.QRect(10, 10, 430, 310))
        self.current_programs_tasks_view.setObjectName("current_programs_tasks_view")
        self.current_programs_tasks_view.setColumnCount(4)
        self.current_programs_tasks_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.current_programs_tasks_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.current_programs_tasks_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.current_programs_tasks_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.current_programs_tasks_view.setHorizontalHeaderItem(3, item)
        self.frame_3 = QtWidgets.QFrame(self.win_current_programs)
        self.frame_3.setGeometry(QtCore.QRect(460, 10, 60, 330))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_clear_all_programs = QtWidgets.QPushButton(self.frame_3)
        self.btn_clear_all_programs.setGeometry(QtCore.QRect(5, 65, 50, 50))
        self.btn_clear_all_programs.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"alternate-background-color: rgb(255, 170, 127);")
        self.btn_clear_all_programs.setObjectName("btn_clear_all_programs")
        self.btn_edit_programs = QtWidgets.QPushButton(self.frame_3)
        self.btn_edit_programs.setGeometry(QtCore.QRect(5, 140, 50, 50))
        self.btn_edit_programs.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);\n"
"alternate-background-color: rgb(85, 170, 127);")
        self.btn_edit_programs.setObjectName("btn_edit_programs")
        self.btn_delete_programs = QtWidgets.QPushButton(self.frame_3)
        self.btn_delete_programs.setGeometry(QtCore.QRect(5, 215, 50, 50))
        self.btn_delete_programs.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);\n"
"alternate-background-color: rgb(255, 0, 0);")
        self.btn_delete_programs.setObjectName("btn_delete_programs")

        self.retranslateUi(current_programs_form)
        QtCore.QMetaObject.connectSlotsByName(current_programs_form)

    def retranslateUi(self, current_programs_form):
        _translate = QtCore.QCoreApplication.translate
        current_programs_form.setWindowTitle(_translate("current_programs_form", "Form"))
        item = self.current_programs_tasks_view.horizontalHeaderItem(0)
        item.setText(_translate("current_programs_form", "Tasks"))
        item = self.current_programs_tasks_view.horizontalHeaderItem(1)
        item.setText(_translate("current_programs_form", "Value"))
        item = self.current_programs_tasks_view.horizontalHeaderItem(2)
        item.setText(_translate("current_programs_form", "Time"))
        item = self.current_programs_tasks_view.horizontalHeaderItem(3)
        item.setText(_translate("current_programs_form", "Limit"))
        self.btn_clear_all_programs.setText(_translate("current_programs_form", "Clear All"))
        self.btn_edit_programs.setText(_translate("current_programs_form", "Edit"))
        self.btn_delete_programs.setText(_translate("current_programs_form", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    current_programs_form = QtWidgets.QWidget()
    ui = Ui_current_programs_form()
    ui.setupUi(current_programs_form)
    current_programs_form.show()
    sys.exit(app.exec_())
