# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/discharge.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_discharge_form(object):
    def setupUi(self, discharge_form):
        discharge_form.setObjectName("discharge_form")
        discharge_form.resize(750, 430)
        self.win_discharge = QtWidgets.QFrame(discharge_form)
        self.win_discharge.setGeometry(QtCore.QRect(0, 0, 750, 430))
        self.win_discharge.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.win_discharge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.win_discharge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.win_discharge.setObjectName("win_discharge")
        self.groupBox = QtWidgets.QGroupBox(self.win_discharge)
        self.groupBox.setGeometry(QtCore.QRect(25, 15, 700, 60))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.set_dis_charge_current_for_discharge = QtWidgets.QLineEdit(self.groupBox)
        self.set_dis_charge_current_for_discharge.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_dis_charge_current_for_discharge.setInputMask("")
        self.set_dis_charge_current_for_discharge.setObjectName("set_dis_charge_current_for_discharge")
        self.set_dis_charge_current_btn_for_discharge = QtWidgets.QPushButton(self.groupBox)
        self.set_dis_charge_current_btn_for_discharge.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_dis_charge_current_btn_for_discharge.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_dis_charge_current_btn_for_discharge.setObjectName("set_dis_charge_current_btn_for_discharge")
        self.groupBox_2 = QtWidgets.QGroupBox(self.win_discharge)
        self.groupBox_2.setGeometry(QtCore.QRect(25, 100, 700, 60))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.set_dis_charge_time_btn_for_discharge = QtWidgets.QPushButton(self.groupBox_2)
        self.set_dis_charge_time_btn_for_discharge.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_dis_charge_time_btn_for_discharge.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_dis_charge_time_btn_for_discharge.setObjectName("set_dis_charge_time_btn_for_discharge")
        self.set_dis_charge_time_for_discharge = QtWidgets.QLineEdit(self.groupBox_2)
        self.set_dis_charge_time_for_discharge.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_dis_charge_time_for_discharge.setObjectName("set_dis_charge_time_for_discharge")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.win_discharge)
        self.groupBox_3.setGeometry(QtCore.QRect(25, 185, 700, 60))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.set_dis_charge_voltage_btn_for_discharge = QtWidgets.QPushButton(self.groupBox_3)
        self.set_dis_charge_voltage_btn_for_discharge.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_dis_charge_voltage_btn_for_discharge.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_dis_charge_voltage_btn_for_discharge.setObjectName("set_dis_charge_voltage_btn_for_discharge")
        self.set_dis_charge_volatge_for_discharge = QtWidgets.QLineEdit(self.groupBox_3)
        self.set_dis_charge_volatge_for_discharge.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_dis_charge_volatge_for_discharge.setObjectName("set_dis_charge_volatge_for_discharge")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.win_discharge)
        self.groupBox_4.setGeometry(QtCore.QRect(25, 355, 700, 60))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.set_optional_alerts_btn_for_discharge = QtWidgets.QPushButton(self.groupBox_4)
        self.set_optional_alerts_btn_for_discharge.setGeometry(QtCore.QRect(600, 5, 50, 50))
        self.set_optional_alerts_btn_for_discharge.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"alternate-background-color: rgb(0, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.set_optional_alerts_btn_for_discharge.setObjectName("set_optional_alerts_btn_for_discharge")
        self.set_optional_alerts_for_discharge = QtWidgets.QLineEdit(self.groupBox_4)
        self.set_optional_alerts_for_discharge.setGeometry(QtCore.QRect(300, 10, 200, 40))
        self.set_optional_alerts_for_discharge.setObjectName("set_optional_alerts_for_discharge")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 150, 40))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(discharge_form)
        QtCore.QMetaObject.connectSlotsByName(discharge_form)

    def retranslateUi(self, discharge_form):
        _translate = QtCore.QCoreApplication.translate
        discharge_form.setWindowTitle(_translate("discharge_form", "Form"))
        self.label.setText(_translate("discharge_form", "CHARGE CURRENT"))
        self.set_dis_charge_current_for_discharge.setText(_translate("discharge_form", "PRESS TO CHANGE"))
        self.set_dis_charge_current_btn_for_discharge.setText(_translate("discharge_form", ">"))
        self.set_dis_charge_time_btn_for_discharge.setText(_translate("discharge_form", ">"))
        self.set_dis_charge_time_for_discharge.setText(_translate("discharge_form", "PRESS TO CHANGE"))
        self.label_2.setText(_translate("discharge_form", "CHARGE TIME"))
        self.set_dis_charge_voltage_btn_for_discharge.setText(_translate("discharge_form", ">"))
        self.set_dis_charge_volatge_for_discharge.setText(_translate("discharge_form", "PRESS TO CHANGE"))
        self.label_3.setText(_translate("discharge_form", "CHARGE VOLTAGE"))
        self.set_optional_alerts_btn_for_discharge.setText(_translate("discharge_form", ">"))
        self.set_optional_alerts_for_discharge.setText(_translate("discharge_form", "PRESS TO CHANGE"))
        self.label_5.setText(_translate("discharge_form", "OPTIONAL ALERT (S)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    discharge_form = QtWidgets.QWidget()
    ui = Ui_discharge_form()
    ui.setupUi(discharge_form)
    discharge_form.show()
    sys.exit(app.exec_())
