# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/num_pad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_number_pad_form(object):
    def setupUi(self, number_pad_form):
        number_pad_form.setObjectName("number_pad_form")
        number_pad_form.resize(750, 430)
        self.win_number_pad = QtWidgets.QFrame(number_pad_form)
        self.win_number_pad.setGeometry(QtCore.QRect(0, 0, 750, 430))
        self.win_number_pad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.win_number_pad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.win_number_pad.setObjectName("win_number_pad")
        self.number_pad = QtWidgets.QFrame(self.win_number_pad)
        self.number_pad.setGeometry(QtCore.QRect(110, 40, 530, 350))
        self.number_pad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.number_pad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.number_pad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.number_pad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.number_pad.setObjectName("number_pad")
        self.btn_1_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_1_num_pad.setGeometry(QtCore.QRect(100, 100, 100, 50))
        self.btn_1_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_1_num_pad.setObjectName("btn_1_num_pad")
        self.btn_2_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_2_num_pad.setGeometry(QtCore.QRect(215, 100, 100, 50))
        self.btn_2_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_2_num_pad.setObjectName("btn_2_num_pad")
        self.btn_3_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_3_num_pad.setGeometry(QtCore.QRect(330, 100, 100, 50))
        self.btn_3_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_3_num_pad.setObjectName("btn_3_num_pad")
        self.btn_4_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_4_num_pad.setGeometry(QtCore.QRect(100, 160, 100, 50))
        self.btn_4_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_4_num_pad.setObjectName("btn_4_num_pad")
        self.btn_5_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_5_num_pad.setGeometry(QtCore.QRect(215, 160, 100, 50))
        self.btn_5_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_5_num_pad.setObjectName("btn_5_num_pad")
        self.btn_6_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_6_num_pad.setGeometry(QtCore.QRect(330, 160, 100, 50))
        self.btn_6_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_6_num_pad.setObjectName("btn_6_num_pad")
        self.btn_7_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_7_num_pad.setGeometry(QtCore.QRect(100, 220, 100, 50))
        self.btn_7_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_7_num_pad.setObjectName("btn_7_num_pad")
        self.btn_8_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_8_num_pad.setGeometry(QtCore.QRect(215, 220, 100, 50))
        self.btn_8_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_8_num_pad.setObjectName("btn_8_num_pad")
        self.btn_9_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_9_num_pad.setGeometry(QtCore.QRect(330, 220, 100, 50))
        self.btn_9_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_9_num_pad.setObjectName("btn_9_num_pad")
        self.btn_semi_colon_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_semi_colon_num_pad.setGeometry(QtCore.QRect(100, 280, 100, 50))
        self.btn_semi_colon_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_semi_colon_num_pad.setObjectName("btn_semi_colon_num_pad")
        self.btn_0_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_0_num_pad.setGeometry(QtCore.QRect(215, 280, 100, 50))
        self.btn_0_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_0_num_pad.setObjectName("btn_0_num_pad")
        self.btn_dot_num_pad = QtWidgets.QPushButton(self.number_pad)
        self.btn_dot_num_pad.setGeometry(QtCore.QRect(330, 280, 100, 50))
        self.btn_dot_num_pad.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_dot_num_pad.setObjectName("btn_dot_num_pad")
        self.num_pad_input_value = QtWidgets.QLineEdit(self.number_pad)
        self.num_pad_input_value.setGeometry(QtCore.QRect(100, 25, 215, 50))
        self.num_pad_input_value.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.num_pad_input_value.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.num_pad_input_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.num_pad_input_value.setReadOnly(False)
        self.num_pad_input_value.setObjectName("num_pad_input_value")
        self.delete_input_value = QtWidgets.QPushButton(self.number_pad)
        self.delete_input_value.setGeometry(QtCore.QRect(330, 25, 100, 50))
        self.delete_input_value.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.delete_input_value.setObjectName("delete_input_value")

        self.retranslateUi(number_pad_form)
        QtCore.QMetaObject.connectSlotsByName(number_pad_form)

    def retranslateUi(self, number_pad_form):
        _translate = QtCore.QCoreApplication.translate
        number_pad_form.setWindowTitle(_translate("number_pad_form", "Form"))
        self.btn_1_num_pad.setText(_translate("number_pad_form", "1"))
        self.btn_2_num_pad.setText(_translate("number_pad_form", "2"))
        self.btn_3_num_pad.setText(_translate("number_pad_form", "3"))
        self.btn_4_num_pad.setText(_translate("number_pad_form", "4"))
        self.btn_5_num_pad.setText(_translate("number_pad_form", "5"))
        self.btn_6_num_pad.setText(_translate("number_pad_form", "6"))
        self.btn_7_num_pad.setText(_translate("number_pad_form", "7"))
        self.btn_8_num_pad.setText(_translate("number_pad_form", "8"))
        self.btn_9_num_pad.setText(_translate("number_pad_form", "9"))
        self.btn_semi_colon_num_pad.setText(_translate("number_pad_form", ":"))
        self.btn_0_num_pad.setText(_translate("number_pad_form", "0"))
        self.btn_dot_num_pad.setText(_translate("number_pad_form", "."))
        self.delete_input_value.setText(_translate("number_pad_form", "<<<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    number_pad_form = QtWidgets.QWidget()
    ui = Ui_number_pad_form()
    ui.setupUi(number_pad_form)
    number_pad_form.show()
    sys.exit(app.exec_())
