# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/stop_next_pause_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stop_next_pause_buttons_form(object):
    def setupUi(self, stop_next_pause_buttons_form):
        stop_next_pause_buttons_form.setObjectName("stop_next_pause_buttons_form")
        stop_next_pause_buttons_form.resize(1002, 80)
        self.stop_next_pause_buttons_win = QtWidgets.QFrame(stop_next_pause_buttons_form)
        self.stop_next_pause_buttons_win.setGeometry(QtCore.QRect(0, 0, 1002, 80))
        self.stop_next_pause_buttons_win.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stop_next_pause_buttons_win.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stop_next_pause_buttons_win.setObjectName("stop_next_pause_buttons_win")
        self.btn_stop_for_all = QtWidgets.QPushButton(self.stop_next_pause_buttons_win)
        self.btn_stop_for_all.setGeometry(QtCore.QRect(50, 5, 120, 70))
        self.btn_stop_for_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"alternate-background-color: rgb(255, 85, 0);")
        self.btn_stop_for_all.setObjectName("btn_stop_for_all")
        self.btn_next_step_for_all = QtWidgets.QPushButton(self.stop_next_pause_buttons_win)
        self.btn_next_step_for_all.setGeometry(QtCore.QRect(700, 5, 120, 70))
        self.btn_next_step_for_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 255);\n"
"alternate-background-color: rgb(85, 0, 255);")
        self.btn_next_step_for_all.setObjectName("btn_next_step_for_all")
        self.btn_pause_for_all = QtWidgets.QPushButton(self.stop_next_pause_buttons_win)
        self.btn_pause_for_all.setGeometry(QtCore.QRect(850, 5, 120, 70))
        self.btn_pause_for_all.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);\n"
"alternate-background-color: rgb(85, 170, 127);")
        self.btn_pause_for_all.setObjectName("btn_pause_for_all")

        self.retranslateUi(stop_next_pause_buttons_form)
        QtCore.QMetaObject.connectSlotsByName(stop_next_pause_buttons_form)

    def retranslateUi(self, stop_next_pause_buttons_form):
        _translate = QtCore.QCoreApplication.translate
        stop_next_pause_buttons_form.setWindowTitle(_translate("stop_next_pause_buttons_form", "Form"))
        self.btn_stop_for_all.setText(_translate("stop_next_pause_buttons_form", "STOP"))
        self.btn_next_step_for_all.setText(_translate("stop_next_pause_buttons_form", "NEXT STEP"))
        self.btn_pause_for_all.setText(_translate("stop_next_pause_buttons_form", "PAUSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    stop_next_pause_buttons_form = QtWidgets.QWidget()
    ui = Ui_stop_next_pause_buttons_form()
    ui.setupUi(stop_next_pause_buttons_form)
    stop_next_pause_buttons_form.show()
    sys.exit(app.exec_())
