# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/view_programs_start_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_view_programs_start_buttons_form(object):
    def setupUi(self, view_programs_start_buttons_form):
        view_programs_start_buttons_form.setObjectName("view_programs_start_buttons_form")
        view_programs_start_buttons_form.resize(1002, 80)
        self.view_programs_start_buttons_win = QtWidgets.QFrame(view_programs_start_buttons_form)
        self.view_programs_start_buttons_win.setGeometry(QtCore.QRect(0, 0, 1002, 80))
        self.view_programs_start_buttons_win.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view_programs_start_buttons_win.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view_programs_start_buttons_win.setObjectName("view_programs_start_buttons_win")
        self.btn_view_settings_home = QtWidgets.QPushButton(self.view_programs_start_buttons_win)
        self.btn_view_settings_home.setGeometry(QtCore.QRect(50, 5, 120, 70))
        self.btn_view_settings_home.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"alternate-background-color: rgb(255, 85, 0);")
        self.btn_view_settings_home.setObjectName("btn_view_settings_home")
        self.btn_programs_settings_home = QtWidgets.QPushButton(self.view_programs_start_buttons_win)
        self.btn_programs_settings_home.setGeometry(QtCore.QRect(200, 5, 120, 70))
        self.btn_programs_settings_home.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 255);\n"
"alternate-background-color: rgb(85, 0, 255);")
        self.btn_programs_settings_home.setObjectName("btn_programs_settings_home")
        self.btn_start_settings_home = QtWidgets.QPushButton(self.view_programs_start_buttons_win)
        self.btn_start_settings_home.setGeometry(QtCore.QRect(850, 5, 120, 70))
        self.btn_start_settings_home.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);\n"
"alternate-background-color: rgb(85, 170, 0);")
        self.btn_start_settings_home.setObjectName("btn_start_settings_home")

        self.retranslateUi(view_programs_start_buttons_form)
        QtCore.QMetaObject.connectSlotsByName(view_programs_start_buttons_form)

    def retranslateUi(self, view_programs_start_buttons_form):
        _translate = QtCore.QCoreApplication.translate
        view_programs_start_buttons_form.setWindowTitle(_translate("view_programs_start_buttons_form", "Form"))
        self.btn_view_settings_home.setText(_translate("view_programs_start_buttons_form", "VIEW..."))
        self.btn_programs_settings_home.setText(_translate("view_programs_start_buttons_form", "PROGRAMS..."))
        self.btn_start_settings_home.setText(_translate("view_programs_start_buttons_form", "START -->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    view_programs_start_buttons_form = QtWidgets.QWidget()
    ui = Ui_view_programs_start_buttons_form()
    ui.setupUi(view_programs_start_buttons_form)
    view_programs_start_buttons_form.show()
    sys.exit(app.exec_())
