# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/wait.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wait_win_form(object):
    def setupUi(self, wait_win_form):
        wait_win_form.setObjectName("wait_win_form")
        wait_win_form.resize(750, 430)
        self.win_wait = QtWidgets.QFrame(wait_win_form)
        self.win_wait.setGeometry(QtCore.QRect(0, 0, 750, 430))
        self.win_wait.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.win_wait.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.win_wait.setFrameShadow(QtWidgets.QFrame.Raised)
        self.win_wait.setObjectName("win_wait")

        self.retranslateUi(wait_win_form)
        QtCore.QMetaObject.connectSlotsByName(wait_win_form)

    def retranslateUi(self, wait_win_form):
        _translate = QtCore.QCoreApplication.translate
        wait_win_form.setWindowTitle(_translate("wait_win_form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wait_win_form = QtWidgets.QWidget()
    ui = Ui_wait_win_form()
    ui.setupUi(wait_win_form)
    wait_win_form.show()
    sys.exit(app.exec_())
